'use client'

import { useState, useEffect } from 'react'
import {
  Target, Star, Shield, Mic, Loader2, FileText, Briefcase,
  ChevronRight, Sparkles, CheckCircle2, Plus, ArrowRight,
  LayoutDashboard, Menu, Download, MessageCircle, Zap, Copy, RefreshCw
} from 'lucide-react'
import { motion, AnimatePresence } from 'framer-motion'
import { GlassCard, GlassCardSection } from '@/components/ui/glass-card'

// --- Types ---

interface Resume {
  id: string
  title: string
  content: any
  job_description_id?: string | null  // Linked job description
}

interface JobDescription {
  id: string
  title: string
  company?: string
  description: string
}

type ToolType = 'swot' | 'star' | 'gap' | 'intro'

// --- Helper: PDF Export ---

async function exportToPDF(title: string, context: { resume?: string, job?: string }, sections: { title: string, content: string | string[], color?: string }[]) {
  try {
    const { jsPDF } = await import('jspdf')
    const doc = new jsPDF()
    const pageWidth = doc.internal.pageSize.getWidth()
    const pageHeight = doc.internal.pageSize.getHeight()
    const margin = 20
    const maxWidth = pageWidth - (margin * 2)
    let yPos = margin

    // Helper: Add Text
    const addText = (text: string, fontSize: number, isBold: boolean = false, color: [number, number, number] = [0, 0, 0]) => {
      doc.setFontSize(fontSize)
      doc.setFont('helvetica', isBold ? 'bold' : 'normal')
      doc.setTextColor(color[0], color[1], color[2])

      const lines = doc.splitTextToSize(text, maxWidth)
      lines.forEach((line: string) => {
        if (yPos + fontSize * 0.5 > pageHeight - margin) {
          doc.addPage()
          yPos = margin
        }
        doc.text(line, margin, yPos)
        yPos += fontSize * 0.5
      })
    }

    // Title
    addText(title.toUpperCase(), 18, true, [106, 71, 255])
    yPos += 10

    // Context
    if (context.resume) {
      addText(`Resume: ${context.resume}`, 10, false, [80, 80, 80])
      yPos += 5
    }
    if (context.job) {
      addText(`Job: ${context.job}`, 10, false, [80, 80, 80])
      yPos += 5
    }

    // Divider
    yPos += 5
    doc.setDrawColor(200, 200, 200)
    doc.line(margin, yPos, pageWidth - margin, yPos)
    yPos += 10

    // Content Sections
    sections.forEach(section => {
      // Check page break for title
      if (yPos + 20 > pageHeight - margin) {
        doc.addPage()
        yPos = margin
      }

      addText(section.title, 12, true, [0, 0, 0])
      yPos += 5

      if (Array.isArray(section.content)) {
        section.content.forEach(item => {
          // Bullet point
          doc.setFontSize(10)
          doc.setFont('helvetica', 'normal')
          doc.setTextColor(60, 60, 60)

          const bullet = "• " + item
          const lines = doc.splitTextToSize(bullet, maxWidth - 5)

          lines.forEach((line: string) => {
            if (yPos + 5 > pageHeight - margin) {
              doc.addPage()
              yPos = margin
            }
            doc.text(line, margin + 5, yPos)
            yPos += 6
          })
        })
      } else {
        doc.setFontSize(10)
        doc.setFont('helvetica', 'normal')
        doc.setTextColor(60, 60, 60)
        const lines = doc.splitTextToSize(section.content, maxWidth)
        lines.forEach((line: string) => {
          if (yPos + 5 > pageHeight - margin) {
            doc.addPage()
            yPos = margin
          }
          doc.text(line, margin, yPos)
          yPos += 6
        })
      }
      yPos += 10
    })

    // Footer
    const footerY = pageHeight - 10
    doc.setFontSize(8)
    doc.setTextColor(150, 150, 150)
    doc.text('Generated by JobFoxy', pageWidth / 2, footerY, { align: 'center' })

    doc.save(`${title.replace(/\s+/g, '-')}-${new Date().toISOString().split('T')[0]}.pdf`)
  } catch (error) {
    console.error('PDF Export Error:', error)
    alert('Failed to generate PDF')
  }
}

// --- Main Page Component ---

export default function CoachingPage() {
  // Context State
  const [resumes, setResumes] = useState<Resume[]>([])
  const [jobDescriptions, setJobDescriptions] = useState<JobDescription[]>([])
  const [selectedResumeId, setSelectedResumeId] = useState<string | null>(null)
  const [selectedJobId, setSelectedJobId] = useState<string | null>(null)
  const [loadingContext, setLoadingContext] = useState(true)

  // Tool State
  const [activeTool, setActiveTool] = useState<ToolType>('swot')
  const [isMobileMenuOpen, setIsMobileMenuOpen] = useState(false)

  // New Job Input State
  const [showNewJobInput, setShowNewJobInput] = useState(false)
  const [newJobTitle, setNewJobTitle] = useState('')
  const [newJobCompany, setNewJobCompany] = useState('')
  const [newJobDescription, setNewJobDescription] = useState('')

  // Load Context Data
  useEffect(() => {
    const fetchData = async () => {
      try {
        // Fetch resumes and job descriptions
        const [resumeRes, jdRes] = await Promise.all([
          fetch('/api/resumes'),
          fetch('/api/job-descriptions')
        ])

        const resumeData = await resumeRes.json()
        const jdData = await jdRes.json()

        let loadedResumes: Resume[] = []
        if (resumeData.success && resumeData.data?.resumes) {
          loadedResumes = resumeData.data.resumes
          setResumes(loadedResumes)

          // Select first resume and its linked job
          if (loadedResumes.length > 0) {
            const firstResume = loadedResumes[0]
            setSelectedResumeId(firstResume.id)

            // Auto-select linked job if available
            if (firstResume.job_description_id) {
              setSelectedJobId(firstResume.job_description_id)
            }
          }
        }

        if (jdData.success && jdData.data?.jobDescriptions) {
          setJobDescriptions(jdData.data.jobDescriptions)
        }
      } catch (error) {
        console.error('Failed to load context:', error)
      } finally {
        setLoadingContext(false)
      }
    }
    fetchData()
  }, [])

  // Auto-select linked job when resume changes
  const handleResumeChange = (resumeId: string) => {
    setSelectedResumeId(resumeId)
    // Check if this resume has a linked job from previous analysis
    const selectedResume = resumes.find(r => r.id === resumeId)
    if (selectedResume?.job_description_id) {
      setSelectedJobId(selectedResume.job_description_id)
    } else {
      // No linked job, reset to general
      setSelectedJobId(null)
    }
  }

  const handleCreateNewJob = async () => {
    if (!newJobTitle.trim() || !newJobDescription.trim()) return

    try {
      const response = await fetch('/api/job-description/create', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          title: newJobTitle.trim(),
          company: newJobCompany.trim() || null,
          description: newJobDescription.trim(),
        }),
      })

      const data = await response.json()

      if (data.success && data.data?.jobDescription) {
        setJobDescriptions([data.data.jobDescription, ...jobDescriptions])
        setSelectedJobId(data.data.jobDescription.id)
        setShowNewJobInput(false)
        setNewJobTitle('')
        setNewJobCompany('')
        setNewJobDescription('')
      }
    } catch (err) {
      console.error('Failed to create job:', err)
    }
  }

  const getContextTitles = () => {
    const resume = resumes.find(r => r.id === selectedResumeId)?.title
    const job = jobDescriptions.find(j => j.id === selectedJobId)?.title
    return { resume, job: job || 'General' }
  }

  const tools = [
    { id: 'swot', name: 'SWOT Analysis', icon: Target, desc: 'Analyze your fit for the role' },
    { id: 'star', name: 'STAR Stories', icon: Star, desc: 'Build behavioral answers' },
    { id: 'gap', name: 'Gap Defense', icon: Shield, desc: 'Address resume weaknesses' },
    { id: 'intro', name: 'Intro Pitch', icon: Mic, desc: 'Perfect your introduction' },
  ]

  return (
    <div className="flex flex-col h-[calc(100vh-2rem)] overflow-hidden">
      {/* ============================================
          HEADER: Context Selectors + Actions
          ============================================ */}
      <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4 px-6 py-4 border-b border-white/5">
        <div className="flex items-center gap-3">
          <div className="p-2 rounded-xl bg-gradient-to-br from-purple-500/20 to-blue-500/20 border border-purple-500/20">
            <LayoutDashboard className="w-6 h-6 text-purple-400" />
          </div>
          <div>
            <h1 className="text-xl font-bold text-white">Career Coaching</h1>
            <p className="text-sm text-white/50">AI-powered interview preparation tools</p>
          </div>
        </div>

        {/* Context Selectors - Inline */}
        <div className="flex items-center gap-3 flex-wrap">
          {/* Resume Selector */}
          <div className="flex items-center gap-2">
            <span className="text-xs text-white/40 uppercase tracking-wider">Resume:</span>
            <select
              value={selectedResumeId || ''}
              onChange={(e) => handleResumeChange(e.target.value)}
              className="px-3 py-2 bg-black/30 border border-white/10 rounded-lg text-white text-sm focus:ring-2 focus:ring-purple-500 outline-none min-w-[180px]"
            >
              <option value="" disabled>Select Resume</option>
              {resumes.map(r => (
                <option key={r.id} value={r.id} className="bg-gray-800">{r.title}</option>
              ))}
            </select>
          </div>

          {/* Job Selector */}
          <div className="flex items-center gap-2">
            <span className="text-xs text-white/40 uppercase tracking-wider">Job:</span>
            {showNewJobInput ? (
              <div className="flex items-center gap-2">
                <input
                  placeholder="Job Title"
                  value={newJobTitle}
                  onChange={e => setNewJobTitle(e.target.value)}
                  className="px-3 py-2 bg-black/30 border border-white/10 rounded-lg text-white text-sm w-32"
                />
                <input
                  placeholder="Company"
                  value={newJobCompany}
                  onChange={e => setNewJobCompany(e.target.value)}
                  className="px-3 py-2 bg-black/30 border border-white/10 rounded-lg text-white text-sm w-28"
                />
                <button
                  onClick={handleCreateNewJob}
                  disabled={!newJobTitle}
                  className="px-3 py-2 bg-purple-500 rounded-lg text-xs font-medium text-white hover:bg-purple-400 transition-colors"
                >
                  Add
                </button>
                <button
                  onClick={() => setShowNewJobInput(false)}
                  className="px-3 py-2 bg-white/10 rounded-lg text-xs font-medium text-white hover:bg-white/20 transition-colors"
                >
                  Cancel
                </button>
              </div>
            ) : (
              <div className="flex items-center gap-2">
                <select
                  value={selectedJobId || ''}
                  onChange={(e) => setSelectedJobId(e.target.value === 'none' ? null : e.target.value)}
                  className="px-3 py-2 bg-black/30 border border-white/10 rounded-lg text-white text-sm focus:ring-2 focus:ring-purple-500 outline-none min-w-[180px]"
                >
                  <option value="none">General / No Specific Job</option>
                  {jobDescriptions.map(j => (
                    <option key={j.id} value={j.id} className="bg-gray-800">{j.title}</option>
                  ))}
                </select>
                <button
                  onClick={() => setShowNewJobInput(true)}
                  className="p-2 bg-white/5 rounded-lg text-purple-400 hover:bg-purple-500/20 transition-colors"
                  title="Add new job"
                >
                  <Plus className="w-4 h-4" />
                </button>
              </div>
            )}
          </div>
        </div>
      </div>

      {/* ============================================
          TABS: Tool Navigation (Horizontal)
          ============================================ */}
      <div className="px-6 py-3 border-b border-white/5 bg-black/20">
        <div className="flex items-center gap-2 overflow-x-auto pb-1">
          {tools.map((tool) => {
            const Icon = tool.icon
            const isActive = activeTool === tool.id
            return (
              <button
                key={tool.id}
                onClick={() => setActiveTool(tool.id as ToolType)}
                className={`
                  flex items-center gap-3 px-5 py-3 rounded-xl font-medium text-sm whitespace-nowrap transition-all duration-200
                  ${isActive
                    ? 'bg-gradient-to-r from-purple-600 to-blue-600 text-white shadow-lg shadow-purple-500/20'
                    : 'bg-white/5 hover:bg-white/10 text-white/70 hover:text-white border border-white/5'}
                `}
              >
                <Icon className={`w-5 h-5 ${isActive ? 'text-white' : 'text-white/50'}`} />
                <span>{tool.name}</span>
              </button>
            )
          })}
        </div>
      </div>

      {/* ============================================
          MAIN CONTENT: Full-Width Tool Views
          ============================================ */}
      <main className="flex-1 overflow-y-auto custom-scrollbar">
        <div className="p-6 lg:p-8">
          <AnimatePresence mode="wait">
            <motion.div
              key={activeTool}
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -10 }}
              transition={{ duration: 0.2 }}
              className="w-full"
            >
              {!selectedResumeId ? (
                <div className="flex flex-col items-center justify-center text-center p-12 bg-white/5 rounded-2xl border border-white/10">
                  <FileText className="w-16 h-16 text-white/20 mb-4" />
                  <h2 className="text-xl font-bold text-white mb-2">Resume Required</h2>
                  <p className="text-white/60">Please select a resume from the header to use the coaching tools.</p>
                </div>
              ) : (
                <>
                  {activeTool === 'swot' && <SwotView resumeId={selectedResumeId} jobId={selectedJobId} contextTitles={getContextTitles()} />}
                  {activeTool === 'star' && <StarView resumeId={selectedResumeId} jobId={selectedJobId} contextTitles={getContextTitles()} />}
                  {activeTool === 'gap' && <GapView resumeId={selectedResumeId} jobId={selectedJobId} contextTitles={getContextTitles()} />}
                  {activeTool === 'intro' && <IntroView resumeId={selectedResumeId} jobId={selectedJobId} contextTitles={getContextTitles()} />}
                </>
              )}
            </motion.div>
          </AnimatePresence>
        </div>
      </main>
    </div>
  )
}

// --- Sub-Components (Tools) ---

function SwotView({ resumeId, jobId, contextTitles }: { resumeId: string; jobId: string | null, contextTitles: any }) {
  const [data, setData] = useState<any>(null)
  const [loading, setLoading] = useState(false)

  // Fetch existing data on load
  useEffect(() => {
    const fetchData = async () => {
      setLoading(true)
      try {
        const queryParams = new URLSearchParams({ resumeId })
        if (jobId) queryParams.append('jobDescriptionId', jobId)

        const res = await fetch(`/api/coaching/swot?${queryParams}`)
        const result = await res.json()

        if (result.success && result.data) {
          setData(result.data)
        } else {
          setData(null) // Reset if no data found
        }
      } catch (e) {
        console.error(e)
      } finally {
        setLoading(false)
      }
    }
    fetchData()
  }, [resumeId, jobId])

  const handleGenerate = async () => {
    setLoading(true)
    try {
      const response = await fetch('/api/coaching/swot', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ resumeId, jobDescriptionId: jobId }),
      })
      const result = await response.json()
      if (result.success) setData(result.data || result)
      else throw new Error(result.error)
    } catch (e) {
      console.error(e)
    } finally {
      setLoading(false)
    }
  }

  const handleExport = () => {
    if (!data) return

    // Helper to convert SWOT items to strings
    const convertToString = (item: any): string => {
      if (typeof item === 'string') return item
      if (item && typeof item === 'object') {
        const parts = []
        if (item.title) parts.push(item.title)
        if (item.insight) parts.push(item.insight)
        if (item.source) parts.push(`(Source: ${item.source})`)
        return parts.join(' - ')
      }
      return String(item)
    }

    exportToPDF('SWOT Analysis', contextTitles, [
      { title: 'Strengths', content: data.strengths?.map(convertToString) || [] },
      { title: 'Weaknesses', content: data.weaknesses?.map(convertToString) || [] },
      { title: 'Opportunities', content: data.opportunities?.map(convertToString) || [] },
      { title: 'Threats', content: data.threats?.map(convertToString) || [] },
    ])
  }

  return (
    <div className="space-y-8">
      <div className="flex items-start justify-between">
        <div>
          <h2 className="text-3xl font-bold text-white mb-2 flex items-center gap-3">
            <Target className="w-8 h-8 text-blue-400" />
            SWOT Analysis
          </h2>
          <p className="text-white/60 text-lg">
            Analyze your strengths, weaknesses, opportunities, and threats.
          </p>
        </div>
        {data && (
          <button onClick={handleExport} className="glass-panel p-2.5 hover:bg-white/10 text-white rounded-xl transition-all">
            <Download className="w-5 h-5" />
          </button>
        )}
      </div>

      {!data && (
        <div className="glass-panel p-12 flex flex-col items-center justify-center text-center">
          <Target className="w-16 h-16 text-white/10 mb-6" />
          <button
            onClick={handleGenerate}
            disabled={loading}
            className="glow-button px-8 py-4 rounded-xl font-bold text-white flex items-center gap-2"
          >
            {loading ? <Loader2 className="animate-spin" /> : <Sparkles className="w-5 h-5" />}
            Generate Analysis
          </button>
        </div>
      )}

      {data && (
        <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-4 gap-6">
          <Card title="Strengths" items={data.strengths} color="green" icon={CheckCircle2} />
          <Card title="Weaknesses" items={data.weaknesses} color="red" icon={Shield} />
          <Card title="Opportunities" items={data.opportunities} color="blue" icon={Target} />
          <Card title="Threats" items={data.threats} color="orange" icon={Briefcase} />

          <div className="md:col-span-2 xl:col-span-4 flex justify-center mt-8">
            <button onClick={handleGenerate} className="text-white/60 hover:text-white flex items-center gap-2 text-sm">
              <Sparkles className="w-4 h-4" /> Regenerate Analysis
            </button>
          </div>
        </div>
      )}
    </div>
  )
}

function Card({ title, items, color, icon: Icon }: any) {
  const colors = {
    green: 'bg-green-500/10 border-green-500/20 text-green-400',
    red: 'bg-red-500/10 border-red-500/20 text-red-400',
    blue: 'bg-blue-500/10 border-blue-500/20 text-blue-400',
    orange: 'bg-orange-500/10 border-orange-500/20 text-orange-400',
  }

  // Helper to render item (handles both string and object formats)
  const renderItem = (item: string | { title?: string; source?: string; insight?: string }) => {
    if (typeof item === 'string') {
      return item
    }
    if (item && typeof item === 'object') {
      return (
        <div className="space-y-1">
          {item.title && <div className="font-medium">{item.title}</div>}
          {item.insight && <div className="text-white/70">{item.insight}</div>}
          {item.source && <div className="text-xs text-white/50 italic mt-1">Source: {item.source}</div>}
        </div>
      )
    }
    return null
  }

  return (
    <div className={`p-6 rounded-xl border ${colors[color as keyof typeof colors]} h-full`}>
      <div className="flex items-center gap-3 mb-4">
        <Icon className="w-5 h-5" />
        <h3 className="font-bold text-lg">{title}</h3>
      </div>
      <ul className="space-y-3">
        {items?.map((item: any, i: number) => (
          <li key={i} className="text-white/80 text-sm leading-relaxed flex gap-2">
            <span className="opacity-50 mt-1">•</span>
            <span className="flex-1">{renderItem(item)}</span>
          </li>
        ))}
      </ul>
    </div>
  )
}

function StarView({ resumeId, jobId, contextTitles }: { resumeId: string; jobId: string | null, contextTitles: any }) {
  // New Question Prediction State
  const [predicting, setPredicting] = useState(false)
  const [predictedQuestions, setPredictedQuestions] = useState<any[]>([])

  // Custom Question State
  const [customQuestion, setCustomQuestion] = useState('')
  const [showCustomInput, setShowCustomInput] = useState(false)

  // Fetch existing STAR stories on mount
  useEffect(() => {
    const fetchExistingStories = async () => {
      try {
        const queryParams = new URLSearchParams({ resumeId })
        const res = await fetch(`/api/coaching/star?${queryParams}`)
        const result = await res.json()

        if (result.success && result.data?.stories && result.data.stories.length > 0) {
          // Transform existing stories into question format
          const existingQuestions = result.data.stories.map((story: any) => ({
            question: story.related_question || story.title,
            type: story.category || 'saved',
            difficulty: 'saved',
            reasoning: 'Previously generated story',
            isExpanded: false,
            answer: {
              situation: story.situation,
              task: story.task,
              action: story.action,
              result: story.result,
            },
            loading: false,
          }))
          setPredictedQuestions(existingQuestions)
        }
      } catch (e) {
        console.error('[Fetch Existing Stories Error]:', e)
      }
    }
    fetchExistingStories()
  }, [resumeId])

  const handlePredict = async (append: boolean = false) => {
    if (!jobId) return
    setPredicting(true)
    try {
      const response = await fetch('/api/coaching/star/predict', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ resumeId, jobDescriptionId: jobId }),
      })
      const result = await response.json()
      if (result.success && result.data?.questions) {
        const newQuestions = result.data.questions.map((q: any) => ({
          ...q,
          isExpanded: false,
          answer: null,
          loading: false
        }))

        if (append) {
          // Filter out duplicates based on question text
          setPredictedQuestions(prev => {
            const existingTexts = new Set(prev.map(p => p.question))
            const uniqueNew = newQuestions.filter((q: any) => !existingTexts.has(q.question))
            return [...prev, ...uniqueNew]
          })
        } else {
          setPredictedQuestions(newQuestions)
        }
      }
    } catch (e) {
      console.error(e)
    } finally {
      setPredicting(false)
    }
  }

  const toggleExpand = (index: number) => {
    setPredictedQuestions(prev => prev.map((q, i) =>
      i === index ? { ...q, isExpanded: !q.isExpanded } : q
    ))
  }

  const generateAnswer = async (index: number) => {
    const question = predictedQuestions[index]
    if (question.answer) return // Already generated

    // Set loading for this specific card
    setPredictedQuestions(prev => prev.map((q, i) =>
      i === index ? { ...q, loading: true } : q
    ))

    try {
      const response = await fetch('/api/coaching/star', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ resumeId, jobDescriptionId: jobId, question: question.question }),
      })
      const result = await response.json()

      if (result.success) {
        setPredictedQuestions(prev => prev.map((q, i) =>
          i === index ? { ...q, answer: result.data || result, loading: false, isExpanded: true } : q
        ))
      } else {
        throw new Error(result.error)
      }
    } catch (e) {
      console.error(e)
      setPredictedQuestions(prev => prev.map((q, i) =>
        i === index ? { ...q, loading: false } : q
      ))
    }
  }

  const addCustomQuestion = () => {
    if (!customQuestion.trim()) return
    const newQ = {
      question: customQuestion,
      type: 'custom',
      difficulty: 'medium',
      reasoning: 'Custom user question',
      isExpanded: true,
      answer: null,
      loading: false
    }
    setPredictedQuestions([newQ, ...predictedQuestions])
    setCustomQuestion('')
    setShowCustomInput(false)
  }

  return (
    <div className="space-y-8 h-full flex flex-col">
      <div className="flex items-start justify-between">
        <div>
          <h2 className="text-3xl font-bold text-white mb-2 flex items-center gap-3">
            <Star className="w-8 h-8 text-yellow-400" />
            STAR Story Builder
          </h2>
          <p className="text-white/60 text-lg">
            Predict interview questions and build structured S.T.A.R. stories.
          </p>
        </div>
      </div>

      {/* Prediction & List Section */}
      {jobId ? (
        <div className="space-y-6">
          {/* Controls */}
          <div className="glass-panel p-6 bg-gradient-to-r from-yellow-900/20 to-transparent flex items-center justify-between">
            <div className="flex items-center gap-3">
              <Sparkles className="w-5 h-5 text-yellow-400" />
              <div>
                <h3 className="font-bold text-white">Interview Predictor</h3>
                <p className="text-xs text-white/50">AI-generated questions based on JD</p>
              </div>
            </div>
            <div className="flex gap-3">
              <button
                onClick={() => setShowCustomInput(!showCustomInput)}
                className="px-4 py-2 bg-white/5 text-white/80 rounded-lg text-sm hover:bg-white/10 transition-all"
              >
                + Custom Question
              </button>
              {predictedQuestions.length > 0 && (
                <button
                  onClick={() => handlePredict(true)}
                  disabled={predicting}
                  className="px-4 py-2 bg-yellow-500/10 text-yellow-400 border border-yellow-500/20 rounded-lg text-sm font-medium hover:bg-yellow-500 hover:text-black transition-all"
                >
                  {predicting ? <Loader2 className="w-3 h-3 animate-spin" /> : '+ More'}
                </button>
              )}
              <button
                onClick={() => handlePredict(false)}
                disabled={predicting}
                className="px-4 py-2 bg-yellow-500 text-black font-bold rounded-lg text-sm hover:bg-yellow-400 transition-all flex items-center gap-2"
              >
                {predicting ? <Loader2 className="w-3 h-3 animate-spin" /> : (predictedQuestions.length > 0 ? 'Refresh All' : 'Predict Questions')}
              </button>
            </div>
          </div>

          {/* Custom Input */}
          <AnimatePresence>
            {showCustomInput && (
              <motion.div
                initial={{ opacity: 0, height: 0 }}
                animate={{ opacity: 1, height: 'auto' }}
                exit={{ opacity: 0, height: 0 }}
                className="overflow-hidden"
              >
                <div className="flex gap-2 mb-4">
                  <input
                    value={customQuestion}
                    onChange={e => setCustomQuestion(e.target.value)}
                    placeholder="Type your own interview question..."
                    className="flex-1 bg-black/40 border border-white/10 rounded-xl px-4 py-3 text-white outline-none focus:border-yellow-500/50"
                    onKeyDown={e => e.key === 'Enter' && addCustomQuestion()}
                  />
                  <button
                    onClick={addCustomQuestion}
                    className="px-6 bg-white/10 text-white rounded-xl font-medium hover:bg-white/20"
                  >
                    Add
                  </button>
                </div>
              </motion.div>
            )}
          </AnimatePresence>

          {/* Question List */}
          <div className="space-y-4">
            {predictedQuestions.length > 0 ? (
              predictedQuestions.map((q, i) => (
                <div key={i} className="glass-panel overflow-hidden border border-white/5 hover:border-white/10 transition-all">
                  {/* Card Header (Question) */}
                  <div
                    onClick={() => toggleExpand(i)}
                    className="p-5 cursor-pointer flex items-start justify-between group"
                  >
                    <div className="flex-1">
                      <div className="flex items-center gap-2 mb-2">
                        <span className="text-xs font-bold uppercase tracking-wider text-yellow-500/80">{q.type}</span>
                        <span className={`text-[10px] px-2 py-0.5 rounded-full border ${q.difficulty === 'hard' ? 'bg-red-500/10 border-red-500/20 text-red-400' : 'bg-green-500/10 border-green-500/20 text-green-400'
                          }`}>
                          {q.difficulty}
                        </span>
                      </div>
                      <h3 className="text-lg font-medium text-white group-hover:text-yellow-100 transition-colors">
                        "{q.question}"
                      </h3>
                      {q.reasoning && <p className="text-white/40 text-sm mt-1">{q.reasoning}</p>}
                    </div>
                    <div className="flex items-center gap-4">
                      {!q.answer && !q.loading && (
                        <button
                          onClick={(e) => {
                            e.stopPropagation()
                            generateAnswer(i)
                          }}
                          className="px-4 py-2 bg-yellow-500/10 text-yellow-400 border border-yellow-500/20 rounded-lg text-sm font-medium hover:bg-yellow-500 hover:text-black transition-all"
                        >
                          Create Answer
                        </button>
                      )}
                      <ChevronRight className={`w-5 h-5 text-white/30 transition-transform duration-300 ${q.isExpanded ? 'rotate-90' : ''}`} />
                    </div>
                  </div>

                  {/* Card Body (Answer) */}
                  <AnimatePresence>
                    {q.isExpanded && (
                      <motion.div
                        initial={{ height: 0, opacity: 0 }}
                        animate={{ height: 'auto', opacity: 1 }}
                        exit={{ height: 0, opacity: 0 }}
                        transition={{ duration: 0.3, ease: 'easeInOut' }}
                      >
                        <div className="p-5 pt-0 border-t border-white/5 bg-black/20">
                          {q.loading ? (
                            <div className="py-8 text-center">
                              <Loader2 className="w-8 h-8 text-yellow-500 animate-spin mx-auto mb-2" />
                              <p className="text-white/50 text-sm">Drafting your STAR story...</p>
                            </div>
                          ) : q.answer ? (
                            <div className="space-y-4 pt-4 relative">
                              {/* PDF Export Button */}
                              <div className="absolute top-0 right-0">
                                <button
                                  onClick={() => exportToPDF('STAR Story', contextTitles, [
                                    { title: 'Question', content: q.question },
                                    { title: 'Situation', content: q.answer.situation },
                                    { title: 'Task', content: q.answer.task },
                                    { title: 'Action', content: q.answer.action },
                                    { title: 'Result', content: q.answer.result },
                                  ])}
                                  className="glass-panel p-2 hover:bg-yellow-900/30 text-white rounded-lg transition-all group"
                                  title="Download as PDF"
                                >
                                  <Download className="w-4 h-4 group-hover:text-yellow-400" />
                                </button>
                              </div>

                              <div className="grid gap-4">
                                <Section title="Situation" content={q.answer.situation} color="text-blue-400" />
                                <Section title="Task" content={q.answer.task} color="text-purple-400" />
                                <Section title="Action" content={q.answer.action} color="text-yellow-400" />
                                <Section title="Result" content={q.answer.result} color="text-green-400" />
                              </div>
                            </div>
                          ) : (
                            <div className="py-4 text-center">
                              <p className="text-white/30 text-sm italic">Click "Create Answer" to generate a story for this question.</p>
                            </div>
                          )}
                        </div>
                      </motion.div>
                    )}
                  </AnimatePresence>
                </div>
              ))
            ) : (
              !predicting && (
                <div className="text-center py-12 border border-dashed border-white/10 rounded-xl">
                  <Sparkles className="w-12 h-12 text-white/10 mx-auto mb-3" />
                  <p className="text-white/40">Click "Predict Questions" to start preparing.</p>
                </div>
              )
            )}
          </div>
        </div>
      ) : (
        <div className="p-4 rounded-xl bg-yellow-500/10 border border-yellow-500/20 text-yellow-200 text-sm">
          Select a Target Job to unlock Question Prediction.
        </div>
      )}
    </div>
  )
}

function Section({ title, content, color }: any) {
  return (
    <div className="glass-panel p-6 border-l-4 border-l-white/20">
      <h3 className={`font-bold mb-2 ${color}`}>{title}</h3>
      <p className="text-white/80 leading-relaxed">{content}</p>
    </div>
  )
}

function GapView({ resumeId, jobId, contextTitles }: { resumeId: string; jobId: string | null, contextTitles: any }) {
  // New Auto-Analysis State
  const [analyzing, setAnalyzing] = useState(false)
  const [detectedGaps, setDetectedGaps] = useState<any[]>([])

  // Custom Gap State
  const [customGapDesc, setCustomGapDesc] = useState('')
  const [customGapType, setCustomGapType] = useState('employment_gap')
  const [showCustomInput, setShowCustomInput] = useState(false)

  // Fetch existing defenses on load
  useEffect(() => {
    const fetchExistingDefenses = async () => {
      try {
        const res = await fetch('/api/coaching/gap-defense')
        const result = await res.json()
        if (result.success && result.data?.defenses) {
          // Transform existing defenses to match the detectedGap structure
          const existing = result.data.defenses.map((d: any) => ({
            type: d.gap_type,
            description: d.gap_description,
            severity: 'saved', // Mark as saved/existing
            context: 'Previously generated',
            isExpanded: false,
            defense: {
              pivot: d.pivot,
              proof: d.proof,
              promise: d.promise
            },
            loading: false
          }))
          setDetectedGaps(prev => {
            // Merge existing with detected, avoiding duplicates if descriptions match exactly
            const existingDescs = new Set(existing.map((e: any) => e.description))
            const filteredPrev = prev.filter(p => !existingDescs.has(p.description))
            return [...existing, ...filteredPrev]
          })
        }
      } catch (e) {
        console.error(e)
      }
    }
    fetchExistingDefenses()
  }, [])

  const handleAnalyze = async () => {
    if (!jobId) return
    setAnalyzing(true)
    try {
      const response = await fetch('/api/coaching/gap-defense/analyze', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ resumeId, jobDescriptionId: jobId }),
      })
      const result = await response.json()
      if (result.success && result.data?.gaps) {
        setDetectedGaps(prev => {
          // Add new detected gaps to the list, avoiding duplicates
          const currentDescs = new Set(prev.map(p => p.description))
          const newGaps = result.data.gaps
            .filter((g: any) => !currentDescs.has(g.description))
            .map((g: any) => ({
              ...g,
              isExpanded: false,
              defense: null,
              loading: false
            }))
          return [...prev, ...newGaps]
        })
      }
    } catch (e) {
      console.error(e)
    } finally {
      setAnalyzing(false)
    }
  }

  const toggleExpand = (index: number) => {
    setDetectedGaps(prev => prev.map((g, i) =>
      i === index ? { ...g, isExpanded: !g.isExpanded } : g
    ))
  }

  const generateDefense = async (index: number) => {
    const gap = detectedGaps[index]
    if (gap.defense) return // Already generated

    setDetectedGaps(prev => prev.map((g, i) =>
      i === index ? { ...g, loading: true } : g
    ))

    try {
      const response = await fetch('/api/coaching/gap-defense', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          resumeId,
          jobDescriptionId: jobId,
          gapType: gap.type,
          gapDescription: gap.description
        }),
      })
      const result = await response.json()

      if (result.success) {
        setDetectedGaps(prev => prev.map((g, i) =>
          i === index ? { ...g, defense: result.data || result, loading: false, isExpanded: true } : g
        ))
      } else {
        throw new Error(result.error)
      }
    } catch (e) {
      console.error(e)
      setDetectedGaps(prev => prev.map((g, i) =>
        i === index ? { ...g, loading: false } : g
      ))
    }
  }

  const addCustomGap = () => {
    if (!customGapDesc.trim()) return
    const newGap = {
      type: customGapType,
      description: customGapDesc,
      severity: 'medium',
      context: 'User reported gap',
      isExpanded: true,
      defense: null,
      loading: false
    }
    setDetectedGaps([newGap, ...detectedGaps])
    setCustomGapDesc('')
    setShowCustomInput(false)
  }

  return (
    <div className="space-y-8 h-full flex flex-col">
      <div className="flex items-start justify-between">
        <div>
          <h2 className="text-3xl font-bold text-white mb-2 flex items-center gap-3">
            <Shield className="w-8 h-8 text-green-400" />
            Gap Defense
          </h2>
          <p className="text-white/60 text-lg">
            Identify weaknesses and turn them into strengths.
          </p>
        </div>
      </div>

      {/* Analysis & List Section */}
      {jobId ? (
        <div className="space-y-6">
          {/* Controls */}
          <div className="glass-panel p-6 bg-gradient-to-r from-green-900/20 to-transparent flex items-center justify-between">
            <div className="flex items-center gap-3">
              <Sparkles className="w-5 h-5 text-green-400" />
              <div>
                <h3 className="font-bold text-white">AI Gap Detector</h3>
                <p className="text-xs text-white/50">Auto-detects missing skills & timeline gaps</p>
              </div>
            </div>
            <div className="flex gap-3">
              <button
                onClick={() => setShowCustomInput(!showCustomInput)}
                className="px-4 py-2 bg-white/5 text-white/80 rounded-lg text-sm hover:bg-white/10 transition-all"
              >
                + Custom Gap
              </button>
              <button
                onClick={handleAnalyze}
                disabled={analyzing}
                className="px-4 py-2 bg-green-500 text-black font-bold rounded-lg text-sm hover:bg-green-400 transition-all flex items-center gap-2"
              >
                {analyzing ? <Loader2 className="w-3 h-3 animate-spin" /> : 'Analyze Resume vs Job'}
              </button>
            </div>
          </div>

          {/* Custom Input */}
          <AnimatePresence>
            {showCustomInput && (
              <motion.div
                initial={{ opacity: 0, height: 0 }}
                animate={{ opacity: 1, height: 'auto' }}
                exit={{ opacity: 0, height: 0 }}
                className="overflow-hidden"
              >
                <div className="flex gap-2 mb-4 items-center">
                  <select
                    value={customGapType}
                    onChange={e => setCustomGapType(e.target.value)}
                    className="bg-black/40 border border-white/10 rounded-xl px-4 py-3 text-white outline-none text-sm w-40"
                  >
                    <option value="employment_gap">Employment Gap</option>
                    <option value="missing_skill">Missing Skill</option>
                    <option value="short_tenure">Short Tenure</option>
                    <option value="experience_mismatch">Mismatch</option>
                  </select>
                  <input
                    value={customGapDesc}
                    onChange={e => setCustomGapDesc(e.target.value)}
                    placeholder="Describe the gap (e.g. 'I lack Python experience')..."
                    className="flex-1 bg-black/40 border border-white/10 rounded-xl px-4 py-3 text-white outline-none focus:border-green-500/50"
                    onKeyDown={e => e.key === 'Enter' && addCustomGap()}
                  />
                  <button
                    onClick={addCustomGap}
                    className="px-6 py-3 bg-white/10 text-white rounded-xl font-medium hover:bg-white/20"
                  >
                    Add
                  </button>
                </div>
              </motion.div>
            )}
          </AnimatePresence>

          {/* Gaps List */}
          <div className="space-y-4">
            {detectedGaps.length > 0 ? (
              detectedGaps.map((gap, i) => (
                <div key={i} className="glass-panel overflow-hidden border border-white/5 hover:border-white/10 transition-all">
                  {/* Card Header */}
                  <div
                    onClick={() => toggleExpand(i)}
                    className="p-5 cursor-pointer flex items-start justify-between group"
                  >
                    <div className="flex-1">
                      <div className="flex items-center gap-2 mb-2">
                        <span className="text-xs font-bold uppercase tracking-wider text-green-500/80">{gap.type.replace('_', ' ')}</span>
                        <span className={`text-[10px] px-2 py-0.5 rounded-full border ${gap.severity === 'high' ? 'bg-red-500/10 border-red-500/20 text-red-400' : 'bg-yellow-500/10 border-yellow-500/20 text-yellow-400'
                          }`}>
                          {gap.severity} severity
                        </span>
                      </div>
                      <h3 className="text-lg font-medium text-white group-hover:text-green-100 transition-colors">
                        {gap.description}
                      </h3>
                    </div>
                    <div className="flex items-center gap-4">
                      {!gap.defense && !gap.loading && (
                        <button
                          onClick={(e) => {
                            e.stopPropagation()
                            generateDefense(i)
                          }}
                          className="px-4 py-2 bg-green-500/10 text-green-400 border border-green-500/20 rounded-lg text-sm font-medium hover:bg-green-500 hover:text-black transition-all"
                        >
                          Defend This
                        </button>
                      )}
                      <ChevronRight className={`w-5 h-5 text-white/30 transition-transform duration-300 ${gap.isExpanded ? 'rotate-90' : ''}`} />
                    </div>
                  </div>

                  {/* Card Body (Defense) */}
                  <AnimatePresence>
                    {gap.isExpanded && (
                      <motion.div
                        initial={{ height: 0, opacity: 0 }}
                        animate={{ height: 'auto', opacity: 1 }}
                        exit={{ height: 0, opacity: 0 }}
                        transition={{ duration: 0.3, ease: 'easeInOut' }}
                      >
                        <div className="p-5 pt-0 border-t border-white/5 bg-black/20">
                          {gap.loading ? (
                            <div className="py-8 text-center">
                              <Loader2 className="w-8 h-8 text-green-500 animate-spin mx-auto mb-2" />
                              <p className="text-white/50 text-sm">Crafting defense strategy...</p>
                            </div>
                          ) : gap.defense ? (
                            <div className="space-y-4 pt-4 relative">
                              {/* PDF Export Button */}
                              <div className="absolute top-0 right-0">
                                <button
                                  onClick={() => exportToPDF('Gap Defense Script', contextTitles, [
                                    { title: 'Gap', content: gap.description },
                                    { title: 'Pivot', content: gap.defense.pivot },
                                    { title: 'Proof', content: gap.defense.proof },
                                    { title: 'Promise', content: gap.defense.promise },
                                  ])}
                                  className="glass-panel p-2 hover:bg-green-900/30 text-white rounded-lg transition-all group"
                                  title="Download as PDF"
                                >
                                  <Download className="w-4 h-4 group-hover:text-green-400" />
                                </button>
                              </div>

                              <Section title="1. The Pivot (Reframe)" content={gap.defense.pivot} color="text-blue-400" />
                              <Section title="2. The Proof (Evidence)" content={gap.defense.proof} color="text-purple-400" />
                              <Section title="3. The Promise (Future)" content={gap.defense.promise} color="text-green-400" />
                            </div>
                          ) : (
                            <div className="py-4 text-center">
                              <p className="text-white/30 text-sm italic">Click "Defend This" to generate a script for this gap.</p>
                            </div>
                          )}
                        </div>
                      </motion.div>
                    )}
                  </AnimatePresence>
                </div>
              ))
            ) : (
              !analyzing && (
                <div className="text-center py-12 border border-dashed border-white/10 rounded-xl">
                  <Sparkles className="w-12 h-12 text-white/10 mx-auto mb-3" />
                  <p className="text-white/40">Click "Analyze Resume vs Job" to detect potential risks.</p>
                </div>
              )
            )}
          </div>
        </div>
      ) : (
        <div className="p-4 rounded-xl bg-yellow-500/10 border border-yellow-500/20 text-yellow-200 text-sm">
          Select a Target Job in the sidebar to enable AI Gap Detection.
        </div>
      )}
    </div>
  )
}

function IntroView({ resumeId, jobId, contextTitles }: { resumeId: string; jobId: string | null, contextTitles: any }) {
  const [style, setStyle] = useState('professional')
  const [data, setData] = useState<any>(null)
  const [loading, setLoading] = useState(false)
  const [copySuccess, setCopySuccess] = useState(false)

  // Fetch existing pitch on load
  useEffect(() => {
    const fetchExistingPitch = async () => {
      setLoading(true)
      try {
        const queryParams = new URLSearchParams({ resumeId })
        if (jobId) queryParams.append('jobDescriptionId', jobId)

        const res = await fetch(`/api/coaching/intro-pitch?${queryParams}`)
        const result = await res.json()

        if (result.success && result.data) {
          setData(result.data)
        } else {
          setData(null)
        }
      } catch (e) {
        console.error(e)
      } finally {
        setLoading(false)
      }
    }
    fetchExistingPitch()
  }, [resumeId, jobId])

  const handleGenerate = async () => {
    setLoading(true)
    try {
      const response = await fetch('/api/coaching/intro-pitch', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ resumeId, jobDescriptionId: jobId, style, targetDuration: 90 }),
      })
      const result = await response.json()
      if (result.success) setData(result.data || result)
      else throw new Error(result.error)
    } catch (e) { console.error(e) } finally { setLoading(false) }
  }

  const handleCopy = async () => {
    if (!data?.pitch_text) return
    try {
      await navigator.clipboard.writeText(data.pitch_text)
      setCopySuccess(true)
      setTimeout(() => setCopySuccess(false), 2000)
    } catch (e) {
      console.error('Failed to copy:', e)
    }
  }

  const handleExport = () => {
    if (!data) return
    exportToPDF('Intro Pitch', contextTitles, [
      { title: 'The Hook', content: data.hook },
      { title: 'Core Message', content: data.core_message },
      { title: 'Call to Action', content: data.call_to_action },
      { title: 'Full Script', content: data.pitch_text },
    ])
  }

  const styleOptions = [
    {
      id: 'professional',
      name: 'Professional',
      icon: Briefcase,
      description: 'Polished, formal, and focused on achievements.',
      gradient: 'from-blue-500 to-cyan-500'
    },
    {
      id: 'conversational',
      name: 'Conversational',
      icon: MessageCircle,
      description: 'Warm, engaging, and builds a personal connection.',
      gradient: 'from-purple-500 to-pink-500'
    },
    {
      id: 'enthusiastic',
      name: 'Enthusiastic',
      icon: Zap,
      description: 'High energy, passionate, and future-focused.',
      gradient: 'from-orange-500 to-red-500'
    }
  ]

  return (
    <div className="space-y-8">
      {/* Header */}
      <div className="flex items-start justify-between">
        <div>
          <h2 className="text-3xl font-bold text-white mb-2 flex items-center gap-3">
            <Mic className="w-8 h-8 text-purple-400" />
            Craft Your Perfect Intro
          </h2>
          <p className="text-white/60 text-lg">
            Create a compelling 30-second "Tell me about yourself" answer.
          </p>
        </div>
        {/* Context Badge */}
        <div className="glass-panel px-3 py-1.5 flex items-center gap-2">
          <FileText className="w-4 h-4 text-purple-400" />
          <span className="text-xs text-white/60">
            Using: <span className="text-white font-medium">{contextTitles.resume}</span>
          </span>
        </div>
      </div>

      {/* Pitch Builder Card */}
      <div className="glass-panel p-8 max-w-4xl mx-auto">
        {/* Style Selection Cards */}
        <div className="space-y-4 mb-8">
          <label className="block text-sm font-bold text-white/80 uppercase tracking-wider">
            Select Your Style
          </label>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            {styleOptions.map((option) => {
              const Icon = option.icon
              const isSelected = style === option.id
              return (
                <motion.button
                  key={option.id}
                  onClick={() => setStyle(option.id)}
                  whileHover={{ scale: 1.02 }}
                  whileTap={{ scale: 0.98 }}
                  className={`
                    relative p-6 rounded-2xl border-2 transition-all duration-300 text-left
                    ${isSelected
                      ? 'border-purple-500 bg-purple-500/10 ring-2 ring-purple-500/50 shadow-lg shadow-purple-500/20'
                      : 'border-white/10 bg-white/5 hover:border-white/20 hover:bg-white/10'
                    }
                  `}
                >
                  {/* Icon */}
                  <div className={`
                    inline-flex p-3 rounded-xl mb-3 bg-gradient-to-br ${option.gradient}
                    ${isSelected ? 'opacity-100' : 'opacity-60'}
                  `}>
                    <Icon className="w-6 h-6 text-white" />
                  </div>

                  {/* Title */}
                  <h3 className={`font-bold mb-2 ${isSelected ? 'text-white' : 'text-white/80'}`}>
                    {option.name}
                  </h3>

                  {/* Description */}
                  <p className={`text-xs leading-relaxed ${isSelected ? 'text-white/70' : 'text-white/50'}`}>
                    {option.description}
                  </p>

                  {/* Selected Indicator */}
                  {isSelected && (
                    <div className="absolute top-3 right-3">
                      <CheckCircle2 className="w-5 h-5 text-purple-400" />
                    </div>
                  )}
                </motion.button>
              )
            })}
          </div>
        </div>

        {/* Generate Button */}
        <div className="flex justify-center">
          <button
            onClick={handleGenerate}
            disabled={loading}
            className="glow-button px-10 py-4 rounded-xl font-bold text-white flex items-center gap-3 disabled:opacity-50"
          >
            {loading ? (
              <>
                <Loader2 className="w-5 h-5 animate-spin" />
                Crafting Your Pitch...
              </>
            ) : (
              <>
                <Sparkles className="w-5 h-5" />
                Generate My Pitch
              </>
            )}
          </button>
        </div>
      </div>

      {/* Output - The Teleprompter */}
      {data && (
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          className="space-y-6 max-w-4xl mx-auto"
        >
          {/* Script Display */}
          <div className="relative">
            {/* PDF Export Button */}
            <div className="absolute top-4 right-4 z-10">
              <button
                onClick={handleExport}
                className="glass-panel p-2.5 hover:bg-purple-900/30 text-white rounded-xl transition-all group"
                title="Download as PDF"
              >
                <Download className="w-5 h-5 group-hover:text-purple-400" />
              </button>
            </div>

            {/* Teleprompter Card */}
            <div className="glass-panel bg-black/40 border-white/20 rounded-2xl overflow-hidden">
              <div className="bg-gradient-to-r from-purple-600/20 to-pink-600/20 px-6 py-3 border-b border-white/10">
                <div className="flex items-center gap-2">
                  <Mic className="w-4 h-4 text-purple-400" />
                  <span className="text-sm font-bold text-white uppercase tracking-wider">
                    Your Pitch Script
                  </span>
                </div>
              </div>

              <div className="p-8 lg:p-12">
                <p className="text-lg lg:text-xl text-white/90 leading-relaxed whitespace-pre-wrap font-light">
                  {data.pitch_text}
                </p>
              </div>

              {/* Action Bar */}
              <div className="px-6 py-4 bg-white/5 border-t border-white/10 flex items-center justify-between">
                <div className="flex gap-3">
                  <button
                    onClick={handleCopy}
                    className="flex items-center gap-2 px-4 py-2 bg-white/10 hover:bg-white/20 rounded-lg text-white text-sm font-medium transition-all"
                  >
                    <Copy className="w-4 h-4" />
                    {copySuccess ? 'Copied!' : 'Copy to Clipboard'}
                  </button>
                  <button
                    onClick={handleGenerate}
                    disabled={loading}
                    className="flex items-center gap-2 px-4 py-2 bg-white/10 hover:bg-white/20 rounded-lg text-white text-sm font-medium transition-all disabled:opacity-50"
                  >
                    <RefreshCw className={`w-4 h-4 ${loading ? 'animate-spin' : ''}`} />
                    Regenerate
                  </button>
                </div>
                <div className="text-xs text-white/40">
                  {data.duration_seconds ? `~${data.duration_seconds}s` : '~30s'}
                </div>
              </div>
            </div>
          </div>

          {/* Component Breakdown */}
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            <div className="p-5 rounded-xl bg-gradient-to-br from-blue-500/10 to-cyan-500/10 border border-blue-500/20">
              <div className="flex items-center gap-2 mb-3">
                <div className="w-2 h-2 rounded-full bg-blue-400"></div>
                <div className="text-xs font-bold text-blue-400 uppercase tracking-wider">The Hook</div>
              </div>
              <p className="text-sm text-white/80 leading-relaxed">{data.hook}</p>
            </div>
            <div className="p-5 rounded-xl bg-gradient-to-br from-purple-500/10 to-pink-500/10 border border-purple-500/20">
              <div className="flex items-center gap-2 mb-3">
                <div className="w-2 h-2 rounded-full bg-purple-400"></div>
                <div className="text-xs font-bold text-purple-400 uppercase tracking-wider">Core Message</div>
              </div>
              <p className="text-sm text-white/80 leading-relaxed">{data.core_message}</p>
            </div>
            <div className="p-5 rounded-xl bg-gradient-to-br from-green-500/10 to-emerald-500/10 border border-green-500/20">
              <div className="flex items-center gap-2 mb-3">
                <div className="w-2 h-2 rounded-full bg-green-400"></div>
                <div className="text-xs font-bold text-green-400 uppercase tracking-wider">Call to Action</div>
              </div>
              <p className="text-sm text-white/80 leading-relaxed">{data.call_to_action}</p>
            </div>
          </div>
        </motion.div>
      )}
    </div>
  )
}
