-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.analysis_results (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  resume_id uuid NOT NULL,
  job_description_id uuid,
  ats_score integer NOT NULL,
  jd_match_score integer,
  skills_fit_score integer NOT NULL,
  analysis_data jsonb NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT analysis_results_pkey PRIMARY KEY (id),
  CONSTRAINT analysis_results_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id),
  CONSTRAINT analysis_results_resume_id_fkey FOREIGN KEY (resume_id) REFERENCES public.resumes(id),
  CONSTRAINT analysis_results_job_description_id_fkey FOREIGN KEY (job_description_id) REFERENCES public.job_descriptions(id)
);
CREATE TABLE public.cover_letters (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  resume_id uuid,
  job_description_id uuid,
  title text NOT NULL DEFAULT 'Cover Letter'::text,
  content text NOT NULL,
  html_content text,
  company_name text,
  position_title text,
  tone text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT cover_letters_pkey PRIMARY KEY (id),
  CONSTRAINT cover_letters_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id),
  CONSTRAINT cover_letters_resume_id_fkey FOREIGN KEY (resume_id) REFERENCES public.resumes(id),
  CONSTRAINT cover_letters_job_description_id_fkey FOREIGN KEY (job_description_id) REFERENCES public.job_descriptions(id)
);
CREATE TABLE public.gap_defenses (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  swot_analysis_id uuid,
  gap_type text NOT NULL,
  gap_description text NOT NULL,
  pivot text,
  proof text,
  promise text,
  is_favorite boolean DEFAULT false,
  use_count integer DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT gap_defenses_pkey PRIMARY KEY (id),
  CONSTRAINT gap_defenses_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id),
  CONSTRAINT gap_defenses_swot_analysis_id_fkey FOREIGN KEY (swot_analysis_id) REFERENCES public.swot_analyses(id)
);
CREATE TABLE public.intro_pitches (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  resume_id uuid,
  job_description_id uuid,
  title text NOT NULL DEFAULT 'Intro Pitch'::text,
  pitch_text text NOT NULL,
  duration_seconds integer,
  hook text,
  core_message text,
  call_to_action text,
  is_active boolean DEFAULT true,
  practice_count integer DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT intro_pitches_pkey PRIMARY KEY (id),
  CONSTRAINT intro_pitches_job_description_id_fkey FOREIGN KEY (job_description_id) REFERENCES public.job_descriptions(id),
  CONSTRAINT intro_pitches_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id),
  CONSTRAINT intro_pitches_resume_id_fkey FOREIGN KEY (resume_id) REFERENCES public.resumes(id)
);
CREATE TABLE public.job_descriptions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  title text NOT NULL,
  company text,
  description text NOT NULL,
  requirements jsonb,
  parsed_skills ARRAY,
  competencies ARRAY,
  is_active boolean DEFAULT true,
  source_url text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT job_descriptions_pkey PRIMARY KEY (id),
  CONSTRAINT job_descriptions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.market_data (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  category text NOT NULL,
  job_title text,
  location text,
  industry text,
  data jsonb NOT NULL,
  expires_at timestamp with time zone NOT NULL,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT market_data_pkey PRIMARY KEY (id)
);
CREATE TABLE public.mock_interview_exchanges (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  mock_interview_id uuid NOT NULL,
  question_text text NOT NULL,
  question_type text,
  question_competency text,
  user_transcript text,
  user_audio_url text,
  answer_duration_seconds integer,
  answer_score numeric,
  star_completeness jsonb,
  follow_up_needed boolean DEFAULT false,
  follow_up_question text,
  follow_up_transcript text,
  follow_up_score numeric,
  exchange_order integer NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT mock_interview_exchanges_pkey PRIMARY KEY (id),
  CONSTRAINT mock_interview_exchanges_mock_interview_id_fkey FOREIGN KEY (mock_interview_id) REFERENCES public.mock_interviews(id)
);
CREATE TABLE public.mock_interviews (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  resume_id uuid,
  job_description_id uuid,
  persona_id text NOT NULL,
  duration_minutes integer NOT NULL DEFAULT 15,
  focus text,
  difficulty text CHECK (difficulty = ANY (ARRAY['easy'::text, 'standard'::text, 'hard'::text])),
  planned_questions jsonb,
  verdict text CHECK (verdict = ANY (ARRAY['strong_hire'::text, 'hire'::text, 'borderline'::text, 'not_ready'::text])),
  overall_score numeric,
  communication_score numeric,
  structure_score numeric,
  role_fit_score numeric,
  technical_depth_score numeric,
  key_strengths ARRAY,
  key_gaps ARRAY,
  improvement_plan jsonb,
  summary text,
  status text DEFAULT 'planned'::text CHECK (status = ANY (ARRAY['planned'::text, 'in_progress'::text, 'completed'::text, 'abandoned'::text])),
  started_at timestamp with time zone,
  completed_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT mock_interviews_pkey PRIMARY KEY (id),
  CONSTRAINT mock_interviews_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id),
  CONSTRAINT mock_interviews_resume_id_fkey FOREIGN KEY (resume_id) REFERENCES public.resumes(id),
  CONSTRAINT mock_interviews_job_description_id_fkey FOREIGN KEY (job_description_id) REFERENCES public.job_descriptions(id)
);
CREATE TABLE public.practice_answers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  question_id uuid NOT NULL,
  user_id uuid NOT NULL,
  transcript text NOT NULL,
  audio_url text,
  overall_score numeric,
  star_analysis jsonb,
  clarity_score numeric,
  relevance_score numeric,
  impact_score numeric,
  strengths ARRAY,
  improvements ARRAY,
  summary text,
  duration_seconds integer,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT practice_answers_pkey PRIMARY KEY (id),
  CONSTRAINT practice_answers_question_id_fkey FOREIGN KEY (question_id) REFERENCES public.practice_questions(id),
  CONSTRAINT practice_answers_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.practice_questions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  session_id uuid NOT NULL,
  question_text text NOT NULL,
  question_category text,
  difficulty text CHECK (difficulty = ANY (ARRAY['easy'::text, 'medium'::text, 'hard'::text])),
  expected_components jsonb,
  order_index integer NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT practice_questions_pkey PRIMARY KEY (id),
  CONSTRAINT practice_questions_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.practice_sessions(id)
);
CREATE TABLE public.practice_sessions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  resume_id uuid,
  job_description_id uuid,
  title text NOT NULL DEFAULT 'Practice Session'::text,
  question_category text,
  total_questions integer DEFAULT 0,
  completed_questions integer DEFAULT 0,
  average_score numeric,
  overall_feedback jsonb,
  status text DEFAULT 'in_progress'::text CHECK (status = ANY (ARRAY['in_progress'::text, 'completed'::text, 'abandoned'::text])),
  started_at timestamp with time zone NOT NULL DEFAULT now(),
  completed_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT practice_sessions_pkey PRIMARY KEY (id),
  CONSTRAINT practice_sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id),
  CONSTRAINT practice_sessions_resume_id_fkey FOREIGN KEY (resume_id) REFERENCES public.resumes(id),
  CONSTRAINT practice_sessions_job_description_id_fkey FOREIGN KEY (job_description_id) REFERENCES public.job_descriptions(id)
);
CREATE TABLE public.profiles (
  id uuid NOT NULL,
  email text NOT NULL,
  full_name text,
  avatar_url text,
  subscription_status text DEFAULT 'free'::text CHECK (subscription_status = ANY (ARRAY['free'::text, 'active'::text, 'past_due'::text, 'canceled'::text, 'trialing'::text])),
  subscription_price_id text,
  subscription_current_period_end timestamp with time zone,
  stripe_customer_id text UNIQUE,
  ai_tokens_used_this_month integer DEFAULT 0,
  practice_sessions_this_month integer DEFAULT 0,
  mock_interviews_this_month integer DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);
CREATE TABLE public.resumes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  title text NOT NULL DEFAULT 'Untitled Resume'::text,
  content jsonb NOT NULL DEFAULT '{}'::jsonb,
  raw_text text,
  is_active boolean DEFAULT true,
  file_url text,
  ats_score integer,
  last_analyzed_at timestamp with time zone,
  analysis_results jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  is_base_version boolean DEFAULT false,
  source_resume_id uuid,
  job_description_id uuid,
  jd_match_score integer,
  CONSTRAINT resumes_pkey PRIMARY KEY (id),
  CONSTRAINT resumes_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id),
  CONSTRAINT resumes_source_resume_id_fkey FOREIGN KEY (source_resume_id) REFERENCES public.resumes(id),
  CONSTRAINT resumes_job_description_id_fkey FOREIGN KEY (job_description_id) REFERENCES public.job_descriptions(id)
);
CREATE TABLE public.star_stories (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  resume_id uuid,
  title text NOT NULL,
  category text,
  related_question text,
  situation text NOT NULL,
  task text NOT NULL,
  action text NOT NULL,
  result text NOT NULL,
  metrics ARRAY,
  skills_demonstrated ARRAY,
  is_favorite boolean DEFAULT false,
  use_count integer DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT star_stories_pkey PRIMARY KEY (id),
  CONSTRAINT star_stories_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id),
  CONSTRAINT star_stories_resume_id_fkey FOREIGN KEY (resume_id) REFERENCES public.resumes(id)
);
CREATE TABLE public.swot_analyses (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  resume_id uuid,
  job_description_id uuid,
  strengths jsonb DEFAULT '[]'::jsonb,
  weaknesses jsonb DEFAULT '[]'::jsonb,
  opportunities jsonb DEFAULT '[]'::jsonb,
  threats jsonb DEFAULT '[]'::jsonb,
  is_active boolean DEFAULT true,
  last_generated_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT swot_analyses_pkey PRIMARY KEY (id),
  CONSTRAINT swot_analyses_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id),
  CONSTRAINT swot_analyses_resume_id_fkey FOREIGN KEY (resume_id) REFERENCES public.resumes(id),
  CONSTRAINT swot_analyses_job_description_id_fkey FOREIGN KEY (job_description_id) REFERENCES public.job_descriptions(id)
);
CREATE TABLE public.usage_tracking (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  resource_type text NOT NULL,
  resource_count integer DEFAULT 1,
  estimated_cost_cents integer,
  session_id uuid,
  metadata jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT usage_tracking_pkey PRIMARY KEY (id),
  CONSTRAINT usage_tracking_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);